command:
  - "sh"
  - "-c"
  - "gunicorn --bind 0.0.0.0:${DATABRICKS_APP_PORT:-8000} --workers 1 --timeout 120 app.main:app"

name: uc-description-generator

resources:
  - name: warehouse
    description: SQL warehouse for UC operations
    warehouse:
      id: "8baced1ff014912d"

env:
  - name: TARGET_CATALOG
    value: "main"
  - name: GOVERNANCE_SCHEMA
    value: "governance"
  - name: MODEL_ENDPOINT
    value: "databricks-meta-llama-3-1-70b-instruct"
  - name: WAREHOUSE_ID
    value: "8baced1ff014912d"
  - name: FLASK_SECRET_KEY
    value: "06f9cece80436035b50577079ca52b2acf5963fc01bacde3ee48075caf45cce1"
