command:
  - "sh"
  - "-c"
  - "gunicorn --bind 0.0.0.0:${DATABRICKS_APP_PORT:-8000} --workers 1 --timeout 120 app.main:app"

name: uc-description-generator

resources:
  - name: warehouse
    description: SQL warehouse for UC operations
    warehouse:
      id: "YOUR_WAREHOUSE_ID_HERE"  # Replace with your SQL Warehouse ID

env:
  - name: TARGET_CATALOG
    value: "main"  # Catalog where governance table will be created
  - name: GOVERNANCE_SCHEMA
    value: "governance"  # Schema for governance table
  - name: MODEL_ENDPOINT
    value: "databricks-meta-llama-3-3-70b-instruct"  # Foundation Model endpoint name
  - name: WAREHOUSE_ID
    value: "YOUR_WAREHOUSE_ID_HERE"  # Replace with your SQL Warehouse ID
  - name: FLASK_SECRET_KEY
    value: "YOUR_SECRET_KEY_HERE"  # Generate with: python -c "import secrets; print(secrets.token_hex(32))"
